OSX_arm64 support
conda-forge/siesta-feedstock pull request #53
Opened 2024-01-25 19:17 UTC by pfebrer

Modification of https://github.com/conda-forge/siesta-feedstock/pull/52 to try to make cross-compilation work.

2024-01-25 19:37 UTC, pfebrer commented
Cool, so I managed to overcome the tests problem. Now it gets to the build phase, but it fails because of a wrong flag for the fortran compiler:

```
[  0%] Building Fortran object _deps/libfdf-build/CMakeFiles/libfdf-lib.dir/src/prec.F90.o
cd $SRC_DIR/obj_cmake/_deps/libfdf-build && $PREFIX/bin/mpifort  -I$SRC_DIR/obj_cmake/_deps/libfdf-build/include -march=armv8.3-a -ftree-vectorize -fPIC -fno-stack-protector -O2 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/siesta-5.0.0rc1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -I$PREFIX/lib -fallow-argument-mismatch -O3 -march=native -mmacosx-version-min=11.0 -Jinclude -fPIC -c $SRC_DIR/obj_cmake/_deps/libfdf-src/src/prec.F90 -o CMakeFiles/libfdf-lib.dir/src/prec.F90.o
f951: Error: unknown value ‘native’ for ‘-march’
f951: note: valid arguments are: armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a armv8.7-a armv8.8-a armv8-r armv9-a
make[2]: *** [_deps/libfdf-build/CMakeFiles/libfdf-lib.dir/build.make:130: _deps/libfdf-build/CMakeFiles/libfdf-lib.dir/src/prec.F90.o] Error 1
make[2]: Leaving directory '$SRC_DIR/obj_cmake'
make[1]: *** [CMakeFiles/Makefile2:2494: _deps/libfdf-build/CMakeFiles/libfdf-lib.dir/all] Error 2
make[1]: Leaving directory '$SRC_DIR/obj_cmake'
make: *** [Makefile:149: all] Error 2
```

It looks like it is correctly set to `-march=armv8.3-a` but then overwritten by `-march=native`. I don't know where this flags come from.

2024-01-25 20:33 UTC, pfebrer commented
@conda-forge-admin, please rerender

2024-02-14 12:19 UTC, zerothi requested changes
There are some more problems that needs fixed, but this is more upstream in the Siesta code.

I'll open an issue to track these details

2024-02-14 12:19 UTC, zerothi commented on recipe/conda_build_config.yaml
> -  - conda-forge siesta_rc
this should stay until 5.0.0 is properly released.

2024-02-14 21:14 UTC, pfebrer commented
The no mpi version seems to work. Nice!!! Let's see if your MPI changes are enough to fix the other ones :)

2024-02-15 07:51 UTC, zerothi commented
> The no mpi version seems to work. Nice!!! Let's see if your MPI changes are enough to fix the other ones :)

That's good, then I would be much more confident it works, you could try and take out the commit (from my PR) as a patch and see?
I only marked it as a draft because I don't know if more needs to be done.

2024-02-15 09:22 UTC, pfebrer commented
Which kinds should I use for arm_64? Should I use your example on the PR:

```
-DSIESTA_REAL_KINDS="4;8"
-DSIESTA_INTEGER_KINDS="4;8"
```

?

2024-02-15 09:24 UTC, zerothi commented
> Which kinds should I use for arm_64? Should I use your example on the PR:
> 
> ```
> -DSIESTA_REAL_KINDS="4;8"
> -DSIESTA_INTEGER_KINDS="4;8"
> ```
> 
> ?

It is compiler specific, not architechture. So I think those should suffice for gcc. Largely all compilers use these values, a few don't... :)

2024-02-15 10:02 UTC, zerothi commented
the patch looks a bit weird... I guess you did `git diff`? One should do `git diff --patch <>` then the message etc. won't stay behind.

2024-02-15 16:59 UTC, pfebrer commented
I use gitlab's graphical interface to get the patch. I don't know how to get the patch easily, since it must patch 5.0.0-beta1 and the MR is against `master`.

2024-02-15 19:59 UTC, pfebrer commented
Yeah I don't know how to apply those changes :sweat_smile: So maybe we can try with the next release.

2024-05-14 07:51 UTC, zerothi commented
@conda-forge-admin, please rerender

2024-05-14 09:59 UTC, merged

2024-05-14 11:12 UTC, zerothi commented
@pfebrer can you check whether this works on arm?

2024-05-14 12:03 UTC, zerothi commented
haha, its just annoying one cannot check it ;)